### ISSUE TITLE
Test suite failures on all architectures but amd64.

### ISSUE THREAD

**Issue by ghisvail** [opengm/opengm#401]
The Debian package was finally accepted for upload to the main archive. However, some autobuilder have reported numerous build failures, mostly due to the testsuite. The different builds are [here](https://buildd.debian.org/status/package.php?p=opengm). As of the time of writing, only packages for the `amd64` architecture were successfully built.

I am quite worried that even [`i386`](https://buildd.debian.org/status/fetch.php?pkg=opengm&arch=i386&ver=2.3.6-1&stamp=1448535779) did not pass. Could you guys have a look? Do you test on 32-bit machines at all?

**Comment by DerThorsten** [comment]
Hi, so it has been quite a while since I compiled and tested on 32 bit.
 By looking at the error I can see that someone used a not explicit 64 bit type (lets say size_t ) 
and now there is some check if the type is big enough.
Should be an easy fix.

terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: EdgeIndexType is to small!

**Comment by joergkappes** [comment]
Hi,
the problem should be fixed with my latest commits. 
However, I have no 32-bit machine to test it.

Joerg

**Comment by ghisvail** [comment]
Good. I'll try the latest version on a 32-bit chroot.

**Comment by ghisvail** [comment]
Still failing for 32-bit builds, this time with the following output:
```
CTEST_OUTPUT_ON_FAILURE=1 ctest --force-new-ctest-process
Test project /build/opengm-2.3.6/obj-i586-linux-gnu
      Start  1: test-partitions
 1/49 Test  #1: test-partitions ..................   Passed    0.23 sec
      Start  2: test-gm-learning-functions
 2/49 Test  #2: test-gm-learning-functions .......   Passed    0.00 sec
      Start  3: test-graphicalmodelmanipulator
 3/49 Test  #3: test-graphicalmodelmanipulator ...   Passed    0.00 sec
      Start  4: test-explicit-storage
 4/49 Test  #4: test-explicit-storage ............   Passed    0.00 sec
      Start  5: test-types
 5/49 Test  #5: test-types .......................   Passed    0.00 sec
      Start  6: test-test-type-sizes-for-hdf5
 6/49 Test  #6: test-test-type-sizes-for-hdf5 ....   Passed    0.00 sec
      Start  7: test-fast-sequence
 7/49 Test  #7: test-fast-sequence ...............   Passed    0.00 sec
      Start  8: test-functions
 8/49 Test  #8: test-functions ...................***Exception: Other  0.02 sec
Functions test...  
  * ExplicitFunction 
  * AbsoluteDifference
  * AbsoluteDifference
  * Constant
  * ModelView
  * Potts
  * PottsN
  * PottsG
  * SquaredDiffrence
  * TruncatedAbsoluteDifference
  * LinearConstraintFunction
terminate called after throwing an instance of 'std::logic_error'
  what():  4.4336 != 4.4336 [line 1294: expectedValues[i] - bounds[i] == *violatedConstraintsWeightsEqualFunctionBegin ]

      Start  9: test-factor
 9/49 Test  #9: test-factor ......................   Passed    0.00 sec
      Start 10: test-discretespaces
10/49 Test #10: test-discretespaces ..............   Passed    0.00 sec
      Start 11: test-graphicalmodel
11/49 Test #11: test-graphicalmodel ..............   Passed    0.01 sec
      Start 12: test-factorgraph
12/49 Test #12: test-factorgraph .................   Passed    0.00 sec
      Start 13: test-graphicalmodeldecomposer
13/49 Test #13: test-graphicalmodeldecomposer ....   Passed    0.25 sec
      Start 14: test-operate
14/49 Test #14: test-operate .....................   Passed    0.24 sec
      Start 15: test-operations
15/49 Test #15: test-operations ..................   Passed    0.00 sec
      Start 16: test-accumulate
16/49 Test #16: test-accumulate ..................   Passed    0.00 sec
      Start 17: test-randomaccessset
17/49 Test #17: test-randomaccessset .............   Passed    0.00 sec
      Start 18: test-tribool
18/49 Test #18: test-tribool .....................   Passed    0.00 sec
      Start 19: test-accessor-iterator
19/49 Test #19: test-accessor-iterator ...........   Passed    0.00 sec
      Start 20: test-random
20/49 Test #20: test-random ......................   Passed    0.01 sec
      Start 21: test-primal-lpbound
21/49 Test #21: test-primal-lpbound ..............   Passed    0.00 sec
      Start 22: test-transportsolver
22/49 Test #22: test-transportsolver .............   Passed    0.00 sec
      Start 23: test-io-hdf5
23/49 Test #23: test-io-hdf5 .....................   Passed    0.03 sec
      Start 24: test-memoryinfo
24/49 Test #24: test-memoryinfo ..................   Passed    0.06 sec
      Start 25: test-lp-solver
25/49 Test #25: test-lp-solver ...................   Passed    0.00 sec
      Start 26: test-indicator-variable
26/49 Test #26: test-indicator-variable ..........   Passed    0.00 sec
      Start 27: test-linear-constraint
27/49 Test #27: test-linear-constraint ...........   Passed    0.00 sec
      Start 28: test-subsequence-iterator
28/49 Test #28: test-subsequence-iterator ........   Passed    0.00 sec
      Start 29: test-lp-functiontransfer
29/49 Test #29: test-lp-functiontransfer .........   Passed    0.00 sec
      Start 30: test-canonicalview
30/49 Test #30: test-canonicalview ...............   Passed    0.09 sec
      Start 31: test-adsal
31/49 Test #31: test-adsal .......................   Passed    0.27 sec
      Start 32: test-nesterov
32/49 Test #32: test-nesterov ....................   Passed    0.73 sec
      Start 33: test-trwsi
33/49 Test #33: test-trwsi .......................   Passed    0.10 sec
      Start 34: test-messagepassing
34/49 Test #34: test-messagepassing ..............   Passed    6.76 sec
      Start 35: test-dynamicprogramming
35/49 Test #35: test-dynamicprogramming ..........   Passed    2.38 sec
      Start 36: test-self-fusion
36/49 Test #36: test-self-fusion .................   Passed   10.09 sec
      Start 37: test-fusion-based-inf
37/49 Test #37: test-fusion-based-inf ............   Passed    0.04 sec
      Start 38: test-icm
38/49 Test #38: test-icm .........................   Passed    0.00 sec
      Start 39: test-bruteforce
39/49 Test #39: test-bruteforce ..................   Passed    0.00 sec
      Start 40: test-lazyflipper
40/49 Test #40: test-lazyflipper .................   Passed    1.45 sec
      Start 41: test-movemaker
41/49 Test #41: test-movemaker ...................   Passed    0.03 sec
      Start 42: test-dualdecomposition
42/49 Test #42: test-dualdecomposition ...........   Passed   11.53 sec
      Start 43: test-astar
43/49 Test #43: test-astar .......................   Passed   11.37 sec
      Start 44: test-2sat
44/49 Test #44: test-2sat ........................   Passed    0.00 sec
      Start 45: test-minstcut
45/49 Test #45: test-minstcut ....................   Passed    0.02 sec
      Start 46: test-graphcut
46/49 Test #46: test-graphcut ....................   Passed   15.02 sec
      Start 47: test-alphabetaswap
47/49 Test #47: test-alphabetaswap ...............   Passed    1.68 sec
      Start 48: test-alphaexpansion
48/49 Test #48: test-alphaexpansion ..............   Passed    3.19 sec
      Start 49: test-qpbo
49/49 Test #49: test-qpbo ........................   Passed    1.41 sec

98% tests passed, 1 tests failed out of 49

Total Test time (real) =  67.05 sec

The following tests FAILED:
	  8 - test-functions (OTHER_FAULT)
Errors while running CTest
```

**Comment by joergkappes** [comment]
I will have a look tomorrow. Seemed that I have missed a line. Should not be a big thing to fix it.

**Comment by ghisvail** [comment]
Good. Thanks for spending some time on this.

**Comment by joergkappes** [comment]
It seemed that You have used version 2.3.6 and not the latest git version, did You.
I have fixed some other lines with my last commit.

Can You check if the problem still exist in the current git-version?

Best
Joerg

**Comment by ghisvail** [comment]
I cherry-picked this [commit](https://github.com/opengm/opengm/commit/3acdc4fb91836caed705a81b8b9d4328078f3bda) on top of the `v2.3.6` release. I'll try out with the latest git snapshot instead.

**Comment by joergkappes** [comment]
This bug is amazing and fixed with commit 03a653e3731c9fd47678f10e54d2f0acdd12a681

Best
Joerg

**Comment by ghisvail** [comment]
All tests are now passing on `i386` using the latest snapshot. Well done.

**Comment by ghisvail** [comment]
FYI, things have [improved](https://buildd.debian.org/status/package.php?p=opengm#problem-1) with the latest update but there are still some test failure on selected architectures. `test-tribool` and `test-io-hdf5` seems to be the main offenders.

**Comment by DerThorsten** [comment]
I am not even sure if we still need our crappy tribool impl.
I'll have a look at it, but I would suggest to just use the one from boost.

**Comment by joergkappes** [comment]
Hi,
I replaced char by int in tribool.hxx with commit 8a3e4c871f0f49952d0f13a62148c32b594451c6.
This avoids to assign -1 to a char which might cause the problem.

Joerg

**Comment by ghisvail** [comment]
Great. It would be nice to have a tagged release containing the latest fixes, as the patch queue for `v2.3.6` starts to become heavy. And please consider fixing #407 which is a big blocker.

**Comment by joergkappes** [comment]
Hi,
I will make a release-tag v2.3.6b if all things are solved. Concerning #407 Thorsten promise me to fix this today. Should be a big thing.

**Comment by ghisvail** [comment]
May I suggest using 2.3.7 instead to keep the semantic versioning
meaningful (here a patch release) ?

**Comment by ghisvail** [comment]
Any news on `v2.3.7`? FYI, given the limited number of architectures the package succeeds to build with, the Ubuntu folks may decide not to ship for the next LTS. Just for the heads up, the LTS freeze is scheduled for February so that still gives you guys a bit of time.

**Comment by joergkappes** [comment]
Hi, we were on a conference the last week and currently looking to get access on a machine with one of the affected architectures. Once we manage this, it should not be a big thing to fix it.

**Comment by ghisvail** [comment]
Any progress on this? Sorry for pushing, but the next freeze for Ubuntu is in a few weeks and it will take some time for the package to get cleared for inclusion, assuming all current test failures are resolved. Cheers.

**Comment by joergkappes** [comment]
Hi, it is quite challenging to fix problems on systems on which one do not have access. As long I am not able to reproduce the problem or at least get a more detailed bug report I can not fix these problems.

**Comment by ghisvail** [comment]
Ok. Could you guys tag a patch release (`2.3.7` ?) of the current snapshot in `master` so I can update the builds. Thanks.

**Comment by joergkappes** [comment]
done, 2.3.7RC

**Comment by ghisvail** [comment]
I have updated the packaging with the latest snapshot on `master`. The report from the builders is available [here](https://buildd.debian.org/status/package.php?p=opengm). The situation was much improved compared to builds with the original `2.3.6` release, so kudos for the work.

It still fails to build on 3 supported architectures (mips, powerpc, s390x) due to a failure of the `test-io-hdf5`.

**Comment by ghisvail** [comment]
Shall I open a different issue for the specific problem on `test-io-hdf5`? This is what `ctest` reports:
```
      Start 23: test-io-hdf5
23/49 Test #23: test-io-hdf5 .....................***Exception: Other  0.03 sec
terminate called after throwing an instance of 'std::runtime_error'
  what():  Data types not equal error.
```
for `mips`, `powerpc`, 's390x', 'hppa' and `ppc64` so far.

**Comment by joergkappes** [comment]
Since I have no of this architectures available for debugging, I would need 
a bit more of information.  Then I can have a look and maybe fix it. Maybe 
it is only a bug in the test itself.

Jörg

Gesendet mit AquaMail für Android
http://www.aqua-mail.com


Am 2. April 2016 12:37:46 schrieb Ghislain Antony Vaillant 
<notifications@github.com>:
